### ISSUE TITLE
Deploy to Heroku is not really required

### ISSUE THREAD

**Issue by deepakarchinnova** [universeworkshops/universe-bot#24]
Hi @brianamarie 

I went through the steps and found out that **Deploy to Heroku** is not really required as Glitch works well even if it is closed.  I tried logging out of glitch and it still worked.

The below is **invalid** 
>Glitch is a fantastic way to test a deployment, but it only runs as long as you have it open in your browser. If you want to have your bot running all the time, you'll need to find another way to deploy.

I was initially thinking of creating a PR but thought I would create an issue to discuss this and later open a PR as the code is clean without any open branches.

Alternatively, I have an idea 💡 to use this material for an Ops team to show the modern way of deployment through heroku and later ask them to create an issue in their fork and a PR to remove the Deploy to Heroku part. This way the workshop would make much sense into how the audience can use it in their daily life, especially highlighting that Ops should document well for the team to scale. 

I want some inputs on this.

**Comment by brianamarie** [comment]
Hi @deepakarchinnova! Thank you for opening this issue. 

> I went through the steps and found out that Deploy to Heroku is not really required as Glitch works well even if it is closed. I tried logging out of glitch and it still worked.

🤔 This is news to me! I'd be curious as to how long it stays running. With Heroku for example, it will "wake up" when new visitors come even after several days. Is the glitch instance still running days later after you have logged out? 

cc @migarjo who worked on this with me at Universe and Satellite



> Alternatively, I have an idea 💡 to use this material for an Ops team to show the modern way of deployment through heroku and later ask them to create an issue in their fork and a PR to remove the Deploy to Heroku part. This way the workshop would make much sense into how the audience can use it in their daily life, especially highlighting that Ops should document well for the team to scale.

I think it's a great idea to extend the activities so they apply more clearly to different teams like an Ops team. But, I'm not sure I fully understand. 

Do you mean going through the workshop as is with Glitch, then with Heroku, then forking again to remove the Heroku instructions? Or, do you mean a separate demo where you showed, then had them fork and follow instructions for Glitch?

**Comment by deepakarchinnova** [comment]
👋 @brianamarie,

Apologies. The glitch server did not respond after 2 hours or so, so this issue stays invalid. 

I had successfully delivered this material yesterday to a Ops team (where the devs are already using GHE) who was really impressed with the output of the material and also they got to know why and how they should use Github and start collaborating with deliveries from the developers. 

> Do you mean going through the workshop as is with Glitch, then with Heroku, then forking again to remove the Heroku instructions? Or, do you mean a separate demo where you showed, then had them fork and follow instructions for Glitch?

I meant the first one that is fork and remove the Heroku instructions, but that totally stands invalid now.

**Comment by brianamarie** [comment]
@deepakarchinnova Okay, sounds good. Thank you for opening this issue!
